UPDATE game_data.especies SET descricao='<p>Os ancestrais dos Kyraths se refugiaram nos biomas subterrâneos acessíveis em Ozamar, um ambiente que favorece a manipulação mysthica, impulsionando o desenvolvimento dos chifres e camadas de pele ‘Sylkranas’, além da alta sensibilidade e outras estruturas relacionadas e características relacionadas a magia. </p>', nome='Kyrath', id_capacidade=1 WHERE id_especie=1;
UPDATE game_data.especies SET descricao='Os Igneray dominam o continente de Imgorath, dividido entre Zalag’Num e Samarak-No’Han. Eles possuem chifres discretos na cabeça, audição aguçada, corpo esguio, cauda longa e pisam com a ponta dos pés. Sua estrutura corporal é esguia e não favorece a força bruta, mas o equilíbrio e velocidade de seus movimentos.', nome='Igneray', id_capacidade=2 WHERE id_especie=2;
UPDATE game_data.especies SET descricao='A espécie humana possui domínios nos continentes de Dihama, Codahri, Galak-Jareh e Shiro Honi. Como descendentes de nômades, eles se destacam, não pela força ou agilidade, mas pela resiliência. Os humanos são famosos pela sua relação com as divindades Ehlorianas, existindo aqueles que apresentam algum tipo de mediunidade.', nome='Humano', id_capacidade=5 WHERE id_especie=5;


UPDATE game_data.racas SET descricao='Os Yoriiz são uma raça de Kyrath....... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Yoriiz', id_capacidade=21, id_especie=1 WHERE id_raca=1;
UPDATE game_data.racas SET descricao='Os Azeraks são uma raça de Igneray.. Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Azerak', id_capacidade=26, id_especie=2 WHERE id_raca=6;
UPDATE game_data.racas SET descricao='Os Saroks são uma raça de Igneray.... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Sarok', id_capacidade=27, id_especie=2 WHERE id_raca=7;
UPDATE game_data.racas SET descricao='Os Mukhrany são uma raça de Andrano...... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Mukhrany', id_capacidade=31, id_especie=3 WHERE id_raca=11;
UPDATE game_data.racas SET descricao='Os Vendruhvio são uma raça de Andrano.. Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Vendruhvio', id_capacidade=32, id_especie=3 WHERE id_raca=12;
UPDATE game_data.racas SET descricao='Os Morthrax são uma raça de Azhad...... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Morthrax', id_capacidade=36, id_especie=4 WHERE id_raca=16;
UPDATE game_data.racas SET descricao='Os Vemyr são uma raça de Azhad............ Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Vemyr', id_capacidade=37, id_especie=4 WHERE id_raca=17;
UPDATE game_data.racas SET descricao='Os Ehleni são uma raça de Humano... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Ehleni', id_capacidade=41, id_especie=5 WHERE id_raca=21;

UPDATE game_data.etnias SET descricao='Os Avynir são parte dos Kyrath Yoriiz, um povo....... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Avynir', id_capacidade=NULL, id_especie=1, id_raca=1 WHERE id_etnia=1;
UPDATE game_data.etnias SET descricao='Os Azeruth são parte dos Igneray Azerak, um povo....... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Azeruth', id_capacidade=NULL, id_especie=2, id_raca=6 WHERE id_etnia=26;
UPDATE game_data.etnias SET descricao='Os Iralik são parte dos Igneray Azerak, um povo....... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Iralik', id_capacidade=NULL, id_especie=2, id_raca=6 WHERE id_etnia=27;
UPDATE game_data.etnias SET descricao='Os Akroy são um povo dentre os Humanos Ehleni, um povo....... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Akroy', id_capacidade=NULL, id_especie=5, id_raca=21 WHERE id_etnia=106;
UPDATE game_data.etnias SET descricao='Os Hendrixo são um povo dentre os Humanos Ehleni, um povo....... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Hendrixo', id_capacidade=NULL, id_especie=5, id_raca=21 WHERE id_etnia=107;
UPDATE game_data.etnias SET descricao='Os Jaremita são um povo dentre os Humanos Ehleni, um povo....... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Jaremita', id_capacidade=NULL, id_especie=5, id_raca=21 WHERE id_etnia=108;
UPDATE game_data.etnias SET descricao='Os Tharyn são parte dos Igneray Saroks, um povo....... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Tharyn', id_capacidade=NULL, id_especie=2, id_raca=7 WHERE id_etnia=31;
UPDATE game_data.etnias SET descricao='Os Venazari são parte dos Igneray Saroks, um povo....... Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry,Lorem ipsum dolor sit amet fell alavalry.', nome='Venazari', id_capacidade=NULL, id_especie=2, id_raca=7 WHERE id_etnia=32;

UPDATE game_data.caracteristicas SET nome='Condicionamento', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='Q', id_capacidade=101 WHERE id_caracteristica=1;
UPDATE game_data.caracteristicas SET nome='Robustez', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='Q', id_capacidade=102 WHERE id_caracteristica=2;
UPDATE game_data.caracteristicas SET nome='Fortitude', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='Q', id_capacidade=103 WHERE id_caracteristica=3;
UPDATE game_data.caracteristicas SET nome='Velocidade', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='Q', id_capacidade=104 WHERE id_caracteristica=4;
UPDATE game_data.caracteristicas SET nome='Furtividade', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='Q', id_capacidade=105 WHERE id_caracteristica=5;
UPDATE game_data.caracteristicas SET nome='Habilidade', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='Q', id_capacidade=106 WHERE id_caracteristica=6;
UPDATE game_data.caracteristicas SET nome='Persuasão', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='Q', id_capacidade=107 WHERE id_caracteristica=7;
UPDATE game_data.caracteristicas SET nome='Simpatia', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='Q', id_capacidade=108 WHERE id_caracteristica=8;
UPDATE game_data.caracteristicas SET nome='Irreverência', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='Q', id_capacidade=109 WHERE id_caracteristica=9;
UPDATE game_data.caracteristicas SET nome='Eloquência', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='Q', id_capacidade=110 WHERE id_caracteristica=10;
UPDATE game_data.caracteristicas SET nome='Sagacidade', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='Q', id_capacidade=111 WHERE id_caracteristica=11;
UPDATE game_data.caracteristicas SET nome='Astúcia', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='Q', id_capacidade=112 WHERE id_caracteristica=12;

UPDATE game_data.caracteristicas SET nome='Fragilidade', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='D', id_capacidade=121 WHERE id_caracteristica=21;
UPDATE game_data.caracteristicas SET nome='Sedentarismo', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='D', id_capacidade=122 WHERE id_caracteristica=22;
UPDATE game_data.caracteristicas SET nome='Debilidade', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='D', id_capacidade=123 WHERE id_caracteristica=23;
UPDATE game_data.caracteristicas SET nome='Desajeito', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='D', id_capacidade=124 WHERE id_caracteristica=24;
UPDATE game_data.caracteristicas SET nome='Imprecisão', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='D', id_capacidade=125 WHERE id_caracteristica=25;
UPDATE game_data.caracteristicas SET nome='Brusquidão', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='D', id_capacidade=126 WHERE id_caracteristica=26;
UPDATE game_data.caracteristicas SET nome='Antipatia', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='D', id_capacidade=127 WHERE id_caracteristica=27;
UPDATE game_data.caracteristicas SET nome='Insegurança', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='D', id_capacidade=128 WHERE id_caracteristica=28;
UPDATE game_data.caracteristicas SET nome='Passividade', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='D', id_capacidade=129 WHERE id_caracteristica=29;
UPDATE game_data.caracteristicas SET nome='Desatenção', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='D', id_capacidade=130 WHERE id_caracteristica=30;
UPDATE game_data.caracteristicas SET nome='Impulsividade', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='D', id_capacidade=131 WHERE id_caracteristica=31;
UPDATE game_data.caracteristicas SET nome='Vulnerabilidade', descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor a ipsum id fringilla.', tipo_qualidade_defeito='D', id_capacidade=132 WHERE id_caracteristica=32;

UPDATE game_data.treinamentos SET nome='Investida', id_capacidade=141, descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu tempus lectus, eget auctor leo. Proin ut magna ipsum. Nulla ultricies lectus eget ante dapibus,' WHERE id_treinamento=1;
UPDATE game_data.treinamentos SET nome='Defesa', id_capacidade=142, descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu tempus lectus, eget auctor leo. Proin ut magna ipsum. Nulla ultricies lectus eget ante dapibus,' WHERE id_treinamento=2;
UPDATE game_data.treinamentos SET nome='Evasão', id_capacidade=143, descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu tempus lectus, eget auctor leo. Proin ut magna ipsum. Nulla ultricies lectus eget ante dapibus,' WHERE id_treinamento=3;
UPDATE game_data.treinamentos SET nome='Resiliência', id_capacidade=144, descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu tempus lectus, eget auctor leo. Proin ut magna ipsum. Nulla ultricies lectus eget ante dapibus,' WHERE id_treinamento=4;
UPDATE game_data.treinamentos SET nome='Velocidade', id_capacidade=145, descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu tempus lectus, eget auctor leo. Proin ut magna ipsum. Nulla ultricies lectus eget ante dapibus,' WHERE id_treinamento=5;
UPDATE game_data.treinamentos SET nome='Mira', id_capacidade=146, descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu tempus lectus, eget auctor leo. Proin ut magna ipsum. Nulla ultricies lectus eget ante dapibus,' WHERE id_treinamento=6;
UPDATE game_data.treinamentos SET nome='Furtividade', id_capacidade=147, descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu tempus lectus, eget auctor leo. Proin ut magna ipsum. Nulla ultricies lectus eget ante dapibus,' WHERE id_treinamento=7;
UPDATE game_data.treinamentos SET nome='Acrobacia', id_capacidade=148, descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu tempus lectus, eget auctor leo. Proin ut magna ipsum. Nulla ultricies lectus eget ante dapibus,' WHERE id_treinamento=8;
UPDATE game_data.treinamentos SET nome='Cognição', id_capacidade=149, descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu tempus lectus, eget auctor leo. Proin ut magna ipsum. Nulla ultricies lectus eget ante dapibus,' WHERE id_treinamento=9;
UPDATE game_data.treinamentos SET nome='Negociação', id_capacidade=150, descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu tempus lectus, eget auctor leo. Proin ut magna ipsum. Nulla ultricies lectus eget ante dapibus,' WHERE id_treinamento=10;
UPDATE game_data.treinamentos SET nome='Intimidação', id_capacidade=151, descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu tempus lectus, eget auctor leo. Proin ut magna ipsum. Nulla ultricies lectus eget ante dapibus,' WHERE id_treinamento=11;
UPDATE game_data.treinamentos SET nome='Empatia', id_capacidade=152, descricao='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu tempus lectus, eget auctor leo. Proin ut magna ipsum. Nulla ultricies lectus eget ante dapibus,' WHERE id_treinamento=12;

UPDATE game_data.tipos_conhecimentos SET nome='Antecedentes', descricao='Os conhecimentos por antecedente são...' WHERE id_tipo_conhecimento=1;
UPDATE game_data.tipos_conhecimentos SET nome='Ofício', descricao='Os conhecimentos de ofício são...' WHERE id_tipo_conhecimento=2;
UPDATE game_data.tipos_conhecimentos SET nome='Teórico', descricao='Os conhecimentos teóricos...' WHERE id_tipo_conhecimento=3;

UPDATE game_data.conhecimentos SET id_tipo_conhecimento=1, nome='Viajante', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=1;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=1, nome='Investigador', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=2;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=1, nome='Criminoso', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=3;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=1, nome='Músico', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=4;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=1, nome='Navegador', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=5;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=1, nome='Militar', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=6;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=1, nome='Nobre', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=7;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=1, nome='Meretriz', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=8;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=1, nome='Performista', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=9;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=1, nome='Escrivão', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=10;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=2, nome='Ferraria', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=21;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=2, nome='Joalheria', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=22;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=2, nome='Carpintaria', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=23;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=2, nome='Tecelagem', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=24;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=2, nome='Alfaiararia ', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=25;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=2, nome='Herbalismo', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=26;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=3, nome='História', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=41;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=3, nome='Política', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=42;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=3, nome='Geografia', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=43;
UPDATE game_data.conhecimentos SET id_tipo_conhecimento=3, nome='Botânica', descricao='Os conhecimentos de xxxx incluem xxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxxxxxxxx, entre outras atribuições relacionadas a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Esse conhecimento é comum para xxxxxx, xxxxxx, xxxxx, xxxx etc.' WHERE id_conhecimento=44;
